using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using HarmonyLib;
using UnityEngine;
using Object = UnityEngine.Object;

namespace CreatureManager;

internal static class CreatureTextureRegistry
{
    private static readonly Dictionary<string, FileTextureEntry> FileTextureCache = new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, Texture2D> ResourceTextureCache = new(StringComparer.OrdinalIgnoreCase);
    private static readonly MethodInfo? LoadImageMethod = AccessTools.Method(
        typeof(ImageConversion),
        nameof(ImageConversion.LoadImage),
        new[] { typeof(Texture2D), typeof(byte[]) });

    private sealed class FileTextureEntry
    {
        internal DateTime LastWriteTimeUtc;
        internal long Length;
        internal Texture2D Texture = null!;
    }

    internal static void Dispose()
    {
        foreach (FileTextureEntry entry in FileTextureCache.Values)
        {
            if (entry.Texture != null)
            {
                Object.Destroy(entry.Texture);
            }
        }

        FileTextureCache.Clear();
    }

    internal static string BuildTextureReferenceText()
    {
        CreatureAssetOwnerCatalog.PrepareMappings();
        List<TextureReferenceEntry> entries = GetAvailableTextureEntries();
        if (entries.Count == 0)
        {
            return "[]\n";
        }

        StringBuilder builder = new();
        builder.AppendLine("# Generated by CreatureManager (texture reference).");
        builder.AppendLine("# Use these names as the textureName value in visual.textures entries.");
        builder.AppendLine("# PNG files in BepInEx/config/CreatureManager/textures can also be used by file name.");
        builder.AppendLine("# Owner sections are best-effort guesses from the Valheim manifest and loaded asset bundles.");
        builder.AppendLine();

        bool wroteSection = false;
        foreach (IGrouping<string, TextureReferenceEntry> section in entries
                     .OrderBy(entry => CreatureReferenceSections.GetOwnerSortBucket(entry.OwnerName))
                     .ThenBy(entry => entry.OwnerName, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
                     .GroupBy(entry => entry.OwnerName, StringComparer.OrdinalIgnoreCase))
        {
            if (wroteSection)
            {
                builder.AppendLine();
            }

            builder.Append("# ===== ");
            builder.Append(section.Key);
            builder.AppendLine(" =====");
            foreach (TextureReferenceEntry entry in section)
            {
                builder.AppendLine(entry.Name);
            }

            wroteSection = true;
        }

        return builder.ToString();
    }

    internal static Texture? GetTexture(string textureName)
    {
        if (string.IsNullOrWhiteSpace(textureName))
        {
            return null;
        }

        string directPath = textureName;
        if (!Path.IsPathRooted(directPath))
        {
            directPath = Path.Combine(CreatureDomainManager.TextureDirectoryPath, textureName);
        }

        if (!Path.HasExtension(directPath))
        {
            directPath += ".png";
        }

        if (File.Exists(directPath))
        {
            return LoadTextureFile(directPath);
        }

        CacheResourceTexturesIfNeeded();
        string lookupName = Path.GetFileNameWithoutExtension(textureName);
        return ResourceTextureCache.TryGetValue(lookupName, out Texture2D texture) ? texture : null;
    }

    private static Texture2D? LoadTextureFile(string path)
    {
        path = Path.GetFullPath(path);
        FileTextureCache.TryGetValue(path, out FileTextureEntry? cached);
        try
        {
            FileInfo file = new(path);
            if (cached?.Texture != null &&
                cached.LastWriteTimeUtc == file.LastWriteTimeUtc &&
                cached.Length == file.Length)
            {
                return cached.Texture;
            }

            byte[] bytes = File.ReadAllBytes(path);
            bool created = cached?.Texture == null;
            Texture2D texture = created ? new Texture2D(2, 2, TextureFormat.RGBA32, false) : cached!.Texture;
            if (!TryLoadImage(texture, bytes))
            {
                CreatureManagerPlugin.Log.LogWarning($"Failed to load texture file {path}.");
                if (created)
                {
                    Object.Destroy(texture);
                }

                return cached?.Texture;
            }

            texture.name = Path.GetFileNameWithoutExtension(path);
            if (cached != null)
            {
                cached.LastWriteTimeUtc = file.LastWriteTimeUtc;
                cached.Length = file.Length;
                return texture;
            }

            FileTextureCache[path] = new FileTextureEntry
            {
                LastWriteTimeUtc = file.LastWriteTimeUtc,
                Length = file.Length,
                Texture = texture
            };
            return texture;
        }
        catch (Exception ex)
        {
            CreatureManagerPlugin.Log.LogWarning($"Failed to load texture file {path}: {ex.Message}");
            return cached?.Texture;
        }
    }

    private static bool TryLoadImage(Texture2D texture, byte[] bytes)
    {
        if (LoadImageMethod == null)
        {
            CreatureManagerPlugin.Log.LogWarning("UnityEngine.ImageConversion.LoadImage was not found.");
            return false;
        }

        return LoadImageMethod.Invoke(null, new object[] { texture, bytes }) is true;
    }

    private static void CacheResourceTexturesIfNeeded()
    {
        if (ResourceTextureCache.Count > 0)
        {
            return;
        }

        RefreshResourceTextureCache();
    }

    private static void RefreshResourceTextureCache()
    {
        foreach (Texture2D texture in Resources.FindObjectsOfTypeAll<Texture2D>().Where(texture => texture != null && texture.GetInstanceID() >= 0))
        {
            if (!ResourceTextureCache.ContainsKey(texture.name))
            {
                ResourceTextureCache[texture.name] = texture;
            }
        }
    }

    private static List<TextureReferenceEntry> GetAvailableTextureEntries()
    {
        RefreshResourceTextureCache();
        return ResourceTextureCache.Keys
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(name => new TextureReferenceEntry
            {
                Name = name,
                OwnerName = CreatureTextureOwnerResolver.GetOwnerName(name)
            })
            .ToList();
    }

    private sealed class TextureReferenceEntry
    {
        public string Name { get; set; } = "";
        public string OwnerName { get; set; } = CreatureReferenceSections.UnknownOwnerName;
    }
}
