using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using UnityEngine;

namespace CreatureManager;

internal static class CreatureReferenceWriter
{
    private const string MainTextureProperty = "_MainTex";

    internal static string BuildReferenceYaml()
    {
        return BuildSectionedPrefabYaml(
            CreaturePrefabRegistry.GetCreaturePrefabs(),
            "compact creature reference",
            AppendReferenceEntry);
    }

    internal static string BuildFullScaffoldYaml()
    {
        HashSet<string> attackAnimationNames = GetKnownAttackAnimationNames();
        return BuildSectionedPrefabYaml(
            CreaturePrefabRegistry.GetCreaturePrefabs(),
            "full creature scaffold",
            (builder, prefab) => AppendFullScaffoldEntry(builder, prefab, attackAnimationNames));
    }

    internal static string BuildAttackReferenceYaml()
    {
        return BuildSectionedPrefabYaml(
            CreaturePrefabRegistry.GetAttackPrefabs(),
            "compact attack reference",
            AppendAttackReferenceEntry);
    }

    internal static string BuildAiReferenceYaml()
    {
        return BuildSectionedPrefabYaml(
            GetAiPrefabs(),
            "compact AI reference",
            AppendAiReferenceEntry);
    }

    internal static string BuildLevelVisualReferenceYaml()
    {
        return BuildSectionedPrefabYaml(
            GetLevelVisualPrefabs(),
            "level visual reference",
            AppendLevelVisualReferenceEntry);
    }

    internal static string BuildCreatureLoadoutReferenceText()
    {
        CreatureAssetOwnerCatalog.PrepareMappings();
        List<CreatureLoadoutReferenceEntry> entries = GetCreatureLoadoutReferenceEntries();
        if (entries.Count == 0)
        {
            return "[]\n";
        }

        StringBuilder builder = new();
        builder.AppendLine("# Generated by CreatureManager (creature loadout reference).");
        builder.AppendLine("# Lists likely creature/NPC equipment ItemDrop prefabs for humanoid.defaultItems and random* loadout fields.");
        builder.AppendLine("# Pure attack holder prefabs such as attack_*, *_shoot, *_shot, and *_melee are omitted.");
        builder.AppendLine("# ItemDrop prefabs with attack animations but no visible renderer are omitted as likely hidden attack holders.");
        builder.AppendLine("# Craftable recipe items are omitted as likely player items.");
        builder.AppendLine("# usedBy is gathered from non-player creature Humanoid loadout fields.");
        builder.AppendLine("# Owner sections are best-effort guesses from the Valheim manifest and loaded asset bundles.");
        builder.AppendLine();

        bool wroteSection = false;
        foreach (IGrouping<string, CreatureLoadoutReferenceEntry> section in entries
                     .OrderBy(entry => CreatureReferenceSections.GetOwnerSortBucket(entry.OwnerName))
                     .ThenBy(entry => entry.OwnerName, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
                     .GroupBy(entry => entry.OwnerName, StringComparer.OrdinalIgnoreCase))
        {
            if (wroteSection)
            {
                builder.AppendLine();
            }

            builder.Append("# ===== ");
            builder.Append(section.Key);
            builder.AppendLine(" =====");

            bool wroteEntry = false;
            foreach (CreatureLoadoutReferenceEntry entry in section)
            {
                if (wroteEntry)
                {
                    builder.AppendLine();
                }

                builder.AppendLine(entry.Name);
                builder.AppendLine($"  usedBy: {FormatInlineList(entry.UsedBy)}");
                if (!string.IsNullOrWhiteSpace(entry.AttackAnimation))
                {
                    builder.AppendLine($"  attackAnimation: {FormatYamlString(entry.AttackAnimation)}");
                }
                wroteEntry = true;
            }

            wroteSection = true;
        }

        return builder.ToString();
    }

    internal static string BuildProjectileReferenceYaml()
    {
        CreatureAssetOwnerCatalog.PrepareMappings();
        List<ProjectileReferenceEntry> entries = GetProjectileReferenceEntries();
        if (entries.Count == 0)
        {
            return "[]\n";
        }

        StringBuilder builder = new();
        builder.AppendLine("# Generated by CreatureManager (projectile reference).");
        builder.AppendLine("# Lists projectile-like prefabs that can be inspected or copied into projectile.yml.");
        builder.AppendLine("# Includes prefabs with root Projectile, Aoe, TriggerSpawnAbility, or SpawnAbility components, plus prefabs referenced by ItemDrop attack projectile fields.");
        builder.AppendLine("# usedByAttacks is reference-only metadata gathered from loaded ItemDrop primary and secondary attacks; projectile.yml ignores it.");
        builder.AppendLine("# projectile and spawnAbility blocks are emitted only when those components exist on the prefab root.");
        builder.AppendLine("# Repeated spawnAbility.spawnPrefabs entries are compacted as Prefab:weight; an omitted weight means 1.");
        builder.AppendLine("# Owner sections are best-effort guesses from the Valheim manifest and loaded asset bundles.");
        builder.AppendLine();

        bool wroteSection = false;
        foreach (IGrouping<string, ProjectileReferenceEntry> section in entries
                     .OrderBy(entry => CreatureReferenceSections.GetOwnerSortBucket(entry.OwnerName))
                     .ThenBy(entry => entry.OwnerName, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
                     .GroupBy(entry => entry.OwnerName, StringComparer.OrdinalIgnoreCase))
        {
            if (wroteSection)
            {
                builder.AppendLine();
            }

            builder.Append("# ===== ");
            builder.Append(section.Key);
            builder.AppendLine(" =====");

            bool wroteEntry = false;
            foreach (ProjectileReferenceEntry entry in section)
            {
                if (wroteEntry)
                {
                    builder.AppendLine();
                }

                AppendListEntry(builder, 0, "prefab", entry.Name);
                AppendLine(builder, 1, $"usedByAttacks: {FormatInlineList(entry.UsedByAttacks)}");
                if (entry.HasProjectile)
                {
                    AppendLine(builder, 1, "projectile:");
                    AppendLine(builder, 2, $"spawnOnHit: {(entry.ProjectileSpawnOnHit == null ? "null" : FormatYamlString(entry.ProjectileSpawnOnHit))}");
                }

                if (entry.HasSpawnAbility)
                {
                    AppendLine(builder, 1, "spawnAbility:");
                    AppendLine(builder, 2, $"spawnPrefabs: {FormatWeightedPrefabInlineList(entry.SpawnAbilityPrefabs)}");
                }

                wroteEntry = true;
            }

            wroteSection = true;
        }

        return builder.ToString();
    }

    private sealed class CreatureLoadoutUsage
    {
        public Dictionary<string, HashSet<string>> UsedBy { get; } = new(StringComparer.OrdinalIgnoreCase);

        public void Add(string creatureName, string slot)
        {
            if (!UsedBy.TryGetValue(creatureName, out HashSet<string> slots))
            {
                slots = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                UsedBy[creatureName] = slots;
            }

            slots.Add(slot);
        }

        public List<string> FormatUsedBy()
        {
            return UsedBy
                .OrderBy(entry => entry.Key, StringComparer.OrdinalIgnoreCase)
                .Select(entry => $"{entry.Key}({string.Join(", ", entry.Value.OrderBy(slot => slot, StringComparer.OrdinalIgnoreCase))})")
                .ToList();
        }

    }

    private sealed class CreatureLoadoutReferenceEntry
    {
        public string Name { get; set; } = "";
        public string OwnerName { get; set; } = CreatureReferenceSections.UnknownOwnerName;
        public string AttackAnimation { get; set; } = "";
        public List<string> UsedBy { get; set; } = new();
    }

    private sealed class ProjectileReferenceUsage
    {
        public GameObject? Prefab { get; set; }
        public HashSet<string> UsedByAttacks { get; } = new(StringComparer.OrdinalIgnoreCase);
    }

    private sealed class ProjectileReferenceEntry
    {
        public string Name { get; set; } = "";
        public string OwnerName { get; set; } = CreatureReferenceSections.UnknownOwnerName;
        public List<string> UsedByAttacks { get; set; } = new();
        public bool HasProjectile { get; set; }
        public string? ProjectileSpawnOnHit { get; set; }
        public bool HasSpawnAbility { get; set; }
        public List<string> SpawnAbilityPrefabs { get; set; } = new();
    }

    private static List<CreatureLoadoutReferenceEntry> GetCreatureLoadoutReferenceEntries()
    {
        Dictionary<string, CreatureLoadoutUsage> usageByItem = CollectCreatureLoadoutUsage();
        HashSet<string> craftableItems = GetCraftableRecipeItemNames();
        List<CreatureLoadoutReferenceEntry> entries = new();

        foreach (GameObject itemPrefab in CreaturePrefabRegistry.GetItemPrefabs())
        {
            if (itemPrefab == null)
            {
                continue;
            }

            string itemName = itemPrefab.name ?? "";
            if (itemName.Length == 0)
            {
                continue;
            }

            ItemDrop? itemDrop = itemPrefab.GetComponent<ItemDrop>();
            if (itemDrop == null)
            {
                continue;
            }

            ItemDrop.ItemData.SharedData shared = itemDrop.m_itemData.m_shared;

            bool hasRecipe = craftableItems.Contains(itemName);
            usageByItem.TryGetValue(itemName, out CreatureLoadoutUsage usage);
            if (!ShouldIncludeCreatureLoadoutItem(itemPrefab, shared, usage, hasRecipe))
            {
                continue;
            }

            entries.Add(new CreatureLoadoutReferenceEntry
            {
                Name = itemName,
                OwnerName = CreaturePrefabOwnerResolver.GetOwnerName(itemName),
                AttackAnimation = GetAttackAnimation(itemPrefab) ?? "",
                UsedBy = usage?.FormatUsedBy() ?? new List<string>()
            });
        }

        return entries;
    }

    private static List<ProjectileReferenceEntry> GetProjectileReferenceEntries()
    {
        Dictionary<string, ProjectileReferenceUsage> usageByProjectile = CollectProjectileUsage();
        Dictionary<string, GameObject> prefabsByName = new(StringComparer.OrdinalIgnoreCase);

        foreach (GameObject prefab in CreaturePrefabRegistry.GetProjectilePrefabs())
        {
            if (prefab != null && !string.IsNullOrWhiteSpace(prefab.name))
            {
                prefabsByName[prefab.name] = prefab;
            }
        }

        foreach (SpawnAbility spawnAbility in Resources.FindObjectsOfTypeAll<SpawnAbility>())
        {
            GameObject? candidate = spawnAbility?.gameObject;
            if (candidate == null || string.IsNullOrWhiteSpace(candidate.name))
            {
                continue;
            }

            GameObject? resolved = CreaturePrefabRegistry.GetPrefab(candidate.name);
            if (resolved != null && resolved.GetComponent<SpawnAbility>() != null)
            {
                prefabsByName[resolved.name] = resolved;
            }
        }

        foreach (KeyValuePair<string, ProjectileReferenceUsage> entry in usageByProjectile)
        {
            if (entry.Value.Prefab != null)
            {
                prefabsByName[entry.Key] = entry.Value.Prefab;
                continue;
            }

            GameObject? resolved = CreaturePrefabRegistry.GetPrefab(entry.Key);
            if (resolved != null)
            {
                prefabsByName[entry.Key] = resolved;
            }
        }

        return prefabsByName
            .OrderBy(entry => entry.Key, StringComparer.OrdinalIgnoreCase)
            .Select(entry =>
            {
                usageByProjectile.TryGetValue(entry.Key, out ProjectileReferenceUsage usage);
                Projectile? projectile = entry.Value.GetComponent<Projectile>();
                SpawnAbility? spawnAbility = entry.Value.GetComponent<SpawnAbility>();
                return new ProjectileReferenceEntry
                {
                    Name = entry.Key,
                    OwnerName = CreaturePrefabOwnerResolver.GetOwnerName(entry.Key),
                    UsedByAttacks = usage?.UsedByAttacks
                        .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
                        .ToList() ?? new List<string>(),
                    HasProjectile = projectile != null,
                    ProjectileSpawnOnHit = GetPrefabNameOrNull(projectile?.m_spawnOnHit),
                    HasSpawnAbility = spawnAbility != null,
                    SpawnAbilityPrefabs = spawnAbility?.m_spawnPrefab?
                        .Where(prefab => prefab != null && !string.IsNullOrWhiteSpace(prefab.name))
                        .Select(prefab => prefab.name)
                        .ToList() ?? new List<string>()
                };
            })
            .ToList();
    }

    private static Dictionary<string, CreatureLoadoutUsage> CollectCreatureLoadoutUsage()
    {
        Dictionary<string, CreatureLoadoutUsage> usageByItem = new(StringComparer.OrdinalIgnoreCase);
        foreach (GameObject creaturePrefab in CreaturePrefabRegistry.GetCreaturePrefabs())
        {
            Humanoid humanoid = creaturePrefab.GetComponent<Humanoid>();
            if (humanoid == null)
            {
                continue;
            }

            AddLoadoutItems(usageByItem, creaturePrefab.name, "defaultItems", humanoid.m_defaultItems);
            AddLoadoutItems(usageByItem, creaturePrefab.name, "randomWeapon", humanoid.m_randomWeapon);
            GetRandomArmorAndHairForOutput(creaturePrefab, humanoid, out GameObject[] randomArmor, out GameObject[] randomHair);
            AddLoadoutItems(usageByItem, creaturePrefab.name, "randomArmor", randomArmor);
            AddLoadoutItems(usageByItem, creaturePrefab.name, "randomHair", randomHair);
            AddLoadoutItems(usageByItem, creaturePrefab.name, "randomShield", humanoid.m_randomShield);
            AddRandomItems(usageByItem, creaturePrefab.name, humanoid.m_randomItems);
            AddRandomSets(usageByItem, creaturePrefab.name, humanoid.m_randomSets);
        }

        return usageByItem;
    }

    private static Dictionary<string, ProjectileReferenceUsage> CollectProjectileUsage()
    {
        Dictionary<string, ProjectileReferenceUsage> usageByProjectile = new(StringComparer.OrdinalIgnoreCase);
        foreach (GameObject itemPrefab in CreaturePrefabRegistry.GetItemPrefabs())
        {
            ItemDrop? itemDrop = itemPrefab.GetComponent<ItemDrop>();
            ItemDrop.ItemData.SharedData? shared = itemDrop?.m_itemData?.m_shared;
            if (shared == null)
            {
                continue;
            }

            AddAttackProjectileUsage(usageByProjectile, itemPrefab.name, shared.m_attack);
            AddAttackProjectileUsage(usageByProjectile, $"{itemPrefab.name}:secondary", shared.m_secondaryAttack);
        }

        return usageByProjectile;
    }

    private static void AddAttackProjectileUsage(Dictionary<string, ProjectileReferenceUsage> usageByProjectile, string attackName, Attack? attack)
    {
        GameObject? projectilePrefab = attack?.m_attackProjectile;
        string projectileName = projectilePrefab?.name ?? "";
        if (projectileName.Length == 0)
        {
            return;
        }

        if (!usageByProjectile.TryGetValue(projectileName, out ProjectileReferenceUsage usage))
        {
            usage = new ProjectileReferenceUsage();
            usageByProjectile[projectileName] = usage;
        }

        usage.Prefab ??= projectilePrefab;
        usage.UsedByAttacks.Add(attackName);
    }

    private static string? GetPrefabNameOrNull(GameObject? prefab)
    {
        string name = prefab?.name ?? "";
        return string.IsNullOrWhiteSpace(name) ? null : name;
    }

    private static void AddLoadoutItems(Dictionary<string, CreatureLoadoutUsage> usageByItem, string creatureName, string slot, IEnumerable<GameObject>? items)
    {
        if (items == null)
        {
            return;
        }

        foreach (GameObject item in items)
        {
            AddLoadoutItem(usageByItem, creatureName, slot, item);
        }
    }

    private static void AddRandomItems(Dictionary<string, CreatureLoadoutUsage> usageByItem, string creatureName, Humanoid.RandomItem[]? items)
    {
        if (items == null)
        {
            return;
        }

        foreach (Humanoid.RandomItem item in items)
        {
            AddLoadoutItem(usageByItem, creatureName, "randomItems", item?.m_prefab);
        }
    }

    private static void AddRandomSets(Dictionary<string, CreatureLoadoutUsage> usageByItem, string creatureName, Humanoid.ItemSet[]? sets)
    {
        if (sets == null)
        {
            return;
        }

        foreach (Humanoid.ItemSet set in sets)
        {
            AddLoadoutItems(usageByItem, creatureName, $"randomSets:{set?.m_name ?? ""}", set?.m_items);
        }
    }

    private static void AddLoadoutItem(Dictionary<string, CreatureLoadoutUsage> usageByItem, string creatureName, string slot, GameObject? item)
    {
        if (item == null || item.GetComponent<ItemDrop>() == null)
        {
            return;
        }

        string itemName = item.name ?? "";
        if (itemName.Length == 0)
        {
            return;
        }

        if (!usageByItem.TryGetValue(itemName, out CreatureLoadoutUsage usage))
        {
            usage = new CreatureLoadoutUsage();
            usageByItem[itemName] = usage;
        }

        usage.Add(creatureName, slot);
    }

    private static HashSet<string> GetCraftableRecipeItemNames()
    {
        HashSet<string> items = new(StringComparer.OrdinalIgnoreCase);
        if (ObjectDB.instance?.m_recipes == null)
        {
            return items;
        }

        foreach (Recipe recipe in ObjectDB.instance.m_recipes)
        {
            if (recipe?.m_item == null)
            {
                continue;
            }

            string itemName = recipe.m_item.gameObject?.name ?? "";
            if (itemName.Length > 0)
            {
                items.Add(itemName);
            }
        }

        return items;
    }

    private static bool ShouldIncludeCreatureLoadoutItem(GameObject itemPrefab, ItemDrop.ItemData.SharedData shared, CreatureLoadoutUsage? usage, bool hasRecipe)
    {
        if (hasRecipe)
        {
            return false;
        }

        if (IsLikelyAttackOnlyItem(itemPrefab, shared))
        {
            return false;
        }

        return IsCreatureLoadoutItemType(shared.m_itemType.ToString()) || usage != null;
    }

    private static bool IsCreatureLoadoutItemType(string itemType)
    {
        return itemType is
            "OneHandedWeapon" or
            "TwoHandedWeapon" or
            "TwoHandedWeaponLeft" or
            "Bow" or
            "Shield" or
            "Helmet" or
            "Chest" or
            "Legs" or
            "Shoulder" or
            "Utility" or
            "Tool" or
            "Torch" or
            "Attach_Atgeir";
    }

    private static bool IsLikelyAttackOnlyItem(GameObject itemPrefab, ItemDrop.ItemData.SharedData shared)
    {
        string name = (itemPrefab.name ?? "").ToLowerInvariant();
        if (name.StartsWith("attack_", StringComparison.Ordinal) ||
            name.Contains("_attack") ||
            name.EndsWith("_shoot", StringComparison.Ordinal) ||
            name.EndsWith("_shot", StringComparison.Ordinal) ||
            name.EndsWith("_melee", StringComparison.Ordinal) ||
            name.Contains("projectile"))
        {
            return true;
        }

        string attackAnimation = GetAttackAnimation(itemPrefab) ?? "";
        string itemType = shared.m_itemType.ToString();
        if (attackAnimation.Length == 0)
        {
            return false;
        }

        if (!HasVisibleRenderer(itemPrefab))
        {
            return true;
        }

        if (string.Equals(itemType, "None", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return !IsCreatureLoadoutItemType(itemType) && !HasItemIcon(shared) && !HasVisibleRenderer(itemPrefab);
    }

    private static bool HasItemIcon(ItemDrop.ItemData.SharedData shared)
    {
        return shared.m_icons != null && shared.m_icons.Any(icon => icon != null);
    }

    private static bool HasVisibleRenderer(GameObject prefab)
    {
        return prefab.GetComponentsInChildren<Renderer>(true)
            .Any(renderer => renderer != null && !IsEffectRenderer(renderer));
    }

    private static List<GameObject> GetAiPrefabs()
    {
        return CreaturePrefabRegistry.GetCreaturePrefabs()
            .Where(prefab => prefab.GetComponent<MonsterAI>() != null || prefab.GetComponent<AnimalAI>() != null)
            .ToList();
    }

    private static List<GameObject> GetLevelVisualPrefabs()
    {
        return CreaturePrefabRegistry.GetCreaturePrefabs()
            .Where(prefab =>
            {
                LevelEffects levelEffects = prefab.GetComponentInChildren<LevelEffects>(true);
                return levelEffects?.m_levelSetups != null && levelEffects.m_levelSetups.Count > 0;
            })
            .ToList();
    }

    private static HashSet<string> GetKnownAttackAnimationNames()
    {
        return CreaturePrefabRegistry.GetAttackPrefabs()
            .Select(GetAttackAnimation)
            .Where(animation => !string.IsNullOrWhiteSpace(animation))
            .Select(animation => animation!)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private static List<string> GetAvailableAttackAnimations(GameObject prefab, HashSet<string> knownAttackAnimationNames)
    {
        List<string> animatorParameters = GetAnimationParameters(prefab);
        if (animatorParameters.Count == 0 || knownAttackAnimationNames.Count == 0)
        {
            return GetConfiguredAttackAnimations(prefab);
        }

        List<string> availableAnimations = animatorParameters
            .Where(knownAttackAnimationNames.Contains)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        return availableAnimations.Count > 0 ? availableAnimations : GetConfiguredAttackAnimations(prefab);
    }

    private static List<string> GetConfiguredAttackAnimations(GameObject prefab)
    {
        Humanoid humanoid = prefab.GetComponent<Humanoid>();
        return humanoid?.m_defaultItems?
            .Where(item => item != null)
            .Select(GetAttackAnimation)
            .Where(animation => !string.IsNullOrWhiteSpace(animation))
            .Select(animation => animation!)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(animation => animation, StringComparer.OrdinalIgnoreCase)
            .ToList() ?? new List<string>();
    }

    private static List<string> GetAnimationParameters(GameObject prefab)
    {
        List<string> directParameters = GetAnimatorParameterNames(
            prefab.GetComponent<Character>()?.m_animator ??
            prefab.GetComponentInChildren<Animator>(true));
        if (directParameters.Count > 0)
        {
            return directParameters;
        }

        return GetInstantiatedAnimatorParameterNames(prefab);
    }

    private static List<string> GetAnimatorParameterNames(Animator? animator)
    {
        if (animator == null)
        {
            return new List<string>();
        }

        return animator.parameters
            .Select(parameter => parameter.name)
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static List<string> GetInstantiatedAnimatorParameterNames(GameObject prefab)
    {
        if (prefab.GetComponentInChildren<Animator>(true) == null)
        {
            return new List<string>();
        }

        GameObject? instance = null;
        bool previousForceDisableInit = ZNetView.m_forceDisableInit;
        try
        {
            ZNetView.m_forceDisableInit = true;
            instance = UnityEngine.Object.Instantiate(prefab);
            return GetAnimatorParameterNames(instance.GetComponentInChildren<Animator>(true));
        }
        catch (Exception ex)
        {
            CreatureManagerPlugin.Log.LogDebug($"Failed to inspect animation parameters for '{prefab.name}': {ex.Message}");
            return new List<string>();
        }
        finally
        {
            ZNetView.m_forceDisableInit = previousForceDisableInit;
            if (instance != null)
            {
                UnityEngine.Object.DestroyImmediate(instance);
            }
        }
    }

    private static string BuildSectionedPrefabYaml(
        List<GameObject> prefabs,
        string artifactKind,
        Action<StringBuilder, GameObject> appendEntry)
    {
        CreatureAssetOwnerCatalog.PrepareMappings();
        if (prefabs.Count == 0)
        {
            return "[]\n";
        }

        StringBuilder builder = new();
        AppendGeneratedHeader(builder, artifactKind);
        CreatureReferenceSections.AppendPrefabSections(builder, prefabs, appendEntry);
        return builder.ToString();
    }

    private static void AppendReferenceEntry(StringBuilder builder, GameObject prefab)
    {
        Character character = prefab.GetComponent<Character>();
        AppendListEntry(builder, 0, "prefab", prefab.name);
        AppendLine(builder, 1, "character:");
        AppendLine(builder, 2, $"name: {FormatYamlString(character.m_name)}");
        AppendLine(builder, 2, $"faction: {CreatureFactionManager.GetDisplayName(character.m_faction)}");
        if (character.m_boss)
        {
            AppendLine(builder, 2, $"boss: {FormatBossTuple(character)}");
        }

        AppendLine(builder, 2, $"health: {FormatFloat(character.m_health)}");
        AppendReferenceDamageModifiers(builder, character.m_damageModifiers, 2);
    }

    private static void AppendFullScaffoldEntry(StringBuilder builder, GameObject prefab, HashSet<string> attackAnimationNames)
    {
        Character character = prefab.GetComponent<Character>();
        AppendListEntry(builder, 0, "prefab", prefab.name);
        AppendLine(builder, 1, "character:");
        AppendLine(builder, 2, $"name: {FormatYamlString(character.m_name)}");
        AppendLine(builder, 2, $"faction: {CreatureFactionManager.GetDisplayName(character.m_faction)}");
        AppendLine(builder, 2, $"boss: {FormatBossTuple(character)}");
        AppendLine(builder, 2, $"defeatSetGlobalKey: {FormatYamlString(character.m_defeatSetGlobalKey)}");
        AppendLine(builder, 2, $"health: {FormatTuple(character.m_health, character.m_regenAllHPTime)}");
        AppendLine(builder, 2, "damageModifiers:");
        AppendDamageModifiers(builder, character.m_damageModifiers, 3);
        AppendLine(builder, 2, $"speed: {FormatTuple(character.m_crouchSpeed, character.m_walkSpeed, character.m_speed, character.m_turnSpeed, character.m_runSpeed, character.m_runTurnSpeed, character.m_acceleration)}");
        AppendLine(builder, 2, $"jump: {FormatTuple(character.m_jumpForce, character.m_jumpForceForward, character.m_jumpForceTiredFactor, character.m_airControl, character.m_jumpStaminaUsage)}");
        AppendLine(builder, 2, $"swim: {FormatTuple(character.m_canSwim, character.m_swimDepth, character.m_swimSpeed, character.m_swimTurnSpeed, character.m_swimAcceleration)}");
        AppendLine(builder, 2, $"flight: {FormatTuple(character.m_flying, character.m_flySlowSpeed, character.m_flyFastSpeed, character.m_flyTurnSpeed)}");
        if (prefab.GetComponent<MonsterAI>() != null || prefab.GetComponent<AnimalAI>() != null)
        {
            AppendLine(builder, 1, $"ai: {FormatYamlString(prefab.name)}");
        }

        AppendHumanoidBlock(builder, prefab, 1);
        AppendLine(builder, 1, $"scale: {FormatFloat(prefab.transform.localScale.x)}");
        AppendLine(builder, 1, $"textures: {FormatInlineList(GetPrimaryTextureSlots(prefab))}");
        AppendAppearance(builder, prefab, 1);
        AppendLine(builder, 1, $"availableAttackAnimations: {FormatInlineList(GetAvailableAttackAnimations(prefab, attackAnimationNames))}");
    }

    private static void AppendAttackReferenceEntry(StringBuilder builder, GameObject prefab)
    {
        ItemDrop itemDrop = prefab.GetComponent<ItemDrop>();
        ItemDrop.ItemData.SharedData shared = itemDrop.m_itemData.m_shared;
        Attack attack = shared.m_attack;

        AppendListEntry(builder, 0, "prefab", prefab.name);
        AppendAttackDamage(builder, 1, shared);
        AppendLine(builder, 1, $"attack: {FormatInlineList(new[] { attack.m_attackType.ToString(), attack.m_attackAnimation })}");
        if (shared.m_attackStatusEffect != null)
        {
            AppendLine(builder, 1, $"statusEffect: {FormatInlineList(new[] { shared.m_attackStatusEffect.name, FormatFloat(shared.m_attackStatusEffectChance) })}");
        }

        if (attack.m_attackProjectile != null)
        {
            AppendLine(builder, 1, $"projectile: {FormatInlineList(new[] { attack.m_attackProjectile.name, FormatFloat(attack.m_projectileVel), FormatFloat(attack.m_projectileAccuracy), attack.m_projectiles.ToString(CultureInfo.InvariantCulture) })}");
        }
        AppendLine(builder, 1, $"ai: {FormatInlineList(new[] { FormatFloat(shared.m_aiAttackInterval), FormatFloat(shared.m_aiAttackRangeMin), FormatFloat(shared.m_aiAttackRange), FormatFloat(shared.m_aiAttackMaxAngle) })}");
    }

    private static void AppendAiReferenceEntry(StringBuilder builder, GameObject prefab)
    {
        MonsterAI monsterAI = prefab.GetComponent<MonsterAI>();
        AnimalAI animalAI = prefab.GetComponent<AnimalAI>();
        BaseAI? baseAI = monsterAI != null ? monsterAI : animalAI;
        if (baseAI == null)
        {
            return;
        }

        AppendListEntry(builder, 0, "ai", prefab.name);
        AppendLine(builder, 1, "baseAI:");
        AppendLine(builder, 2, $"senses: {FormatInlineRawList(FormatFloat(baseAI.m_viewRange), FormatFloat(baseAI.m_viewAngle), FormatFloat(baseAI.m_hearRange), FormatBool(baseAI.m_mistVision))}");
        AppendLine(builder, 2, $"idleSound: {FormatInlineRawList(FormatFloat(baseAI.m_idleSoundInterval), FormatFloat(baseAI.m_idleSoundChance))}");
        AppendLine(builder, 2, $"movement: {FormatInlineRawList(FormatBool(baseAI.m_patrol), baseAI.m_pathAgentType.ToString(), FormatFloat(baseAI.m_moveMinAngle), FormatBool(baseAI.m_smoothMovement))}");
        if (baseAI.m_serpentMovement)
        {
            AppendLine(builder, 2, $"serpent: {FormatInlineRawList(FormatBool(baseAI.m_serpentMovement), FormatFloat(baseAI.m_serpentTurnRadius))}");
        }

        AppendLine(builder, 2, $"randomMove: {FormatInlineRawList(FormatFloat(baseAI.m_jumpInterval), FormatFloat(baseAI.m_randomCircleInterval), FormatFloat(baseAI.m_randomMoveInterval), FormatFloat(baseAI.m_randomMoveRange))}");
        if (baseAI.m_randomFly)
        {
            AppendLine(builder, 2, $"flight: {FormatInlineRawList(FormatBool(baseAI.m_randomFly), FormatFloat(baseAI.m_chanceToTakeoff), FormatFloat(baseAI.m_chanceToLand), FormatFloat(baseAI.m_groundDuration), FormatFloat(baseAI.m_airDuration), FormatFloat(baseAI.m_maxLandAltitude), FormatFloat(baseAI.m_takeoffTime), FormatFloat(baseAI.m_flyAltitudeMin), FormatFloat(baseAI.m_flyAltitudeMax), FormatFloat(baseAI.m_flyAbsMinAltitude))}");
        }

        AppendLine(builder, 2, $"avoid: {FormatInlineRawList(FormatBool(baseAI.m_avoidFire), FormatBool(baseAI.m_afraidOfFire), FormatBool(baseAI.m_avoidWater), FormatBool(baseAI.m_avoidLava), FormatBool(baseAI.m_skipLavaTargets), FormatBool(baseAI.m_avoidLavaFlee))}");
        AppendLine(builder, 2, $"flee: {FormatInlineRawList(FormatFloat(baseAI.m_fleeRange), FormatFloat(baseAI.m_fleeAngle), FormatFloat(baseAI.m_fleeInterval))}");
        AppendLine(builder, 2, $"aggressive: {FormatInlineRawList(FormatBool(baseAI.m_aggravatable), FormatBool(baseAI.m_passiveAggresive))}");
        if (HasAnyMessage(baseAI))
        {
            AppendLine(builder, 2, $"messages: {FormatInlineList(new[] { baseAI.m_spawnMessage, baseAI.m_deathMessage, baseAI.m_alertedMessage })}");
        }

        if (monsterAI != null)
        {
            AppendLine(builder, 1, "monsterAI:");
            AppendLine(builder, 2, $"alertRange: {FormatFloat(monsterAI.m_alertRange)}");
            AppendLine(builder, 2, $"hunt: {FormatInlineRawList(FormatBool(monsterAI.m_enableHuntPlayer), FormatBool(monsterAI.m_attackPlayerObjects), monsterAI.m_privateAreaTriggerTreshold.ToString(CultureInfo.InvariantCulture))}");
            AppendLine(builder, 2, $"chase: {FormatInlineRawList(FormatFloat(monsterAI.m_interceptTimeMin), FormatFloat(monsterAI.m_interceptTimeMax), FormatFloat(monsterAI.m_maxChaseDistance), FormatFloat(monsterAI.m_minAttackInterval))}");
            AppendLine(builder, 2, $"circle: {FormatInlineRawList(FormatFloat(monsterAI.m_circleTargetInterval), FormatFloat(monsterAI.m_circleTargetDuration), FormatFloat(monsterAI.m_circleTargetDistance))}");
            AppendLine(builder, 2, $"hurtFlee: {FormatInlineRawList(FormatBool(monsterAI.m_fleeIfHurtWhenTargetCantBeReached), FormatFloat(monsterAI.m_fleeUnreachableSinceAttacking), FormatFloat(monsterAI.m_fleeUnreachableSinceHurt), FormatBool(monsterAI.m_fleeIfNotAlerted), FormatFloat(monsterAI.m_fleeIfLowHealth), FormatFloat(monsterAI.m_fleeTimeSinceHurt), FormatBool(monsterAI.m_fleeInLava))}");
            AppendLine(builder, 2, $"charge: {FormatInlineRawList(FormatBool(monsterAI.m_circulateWhileCharging), FormatBool(monsterAI.m_circulateWhileChargingFlying))}");
            AppendLine(builder, 2, $"sleep: {FormatInlineRawList(FormatBool(monsterAI.m_sleeping), FormatFloat(monsterAI.m_wakeupRange), FormatBool(monsterAI.m_noiseWakeup), FormatFloat(monsterAI.m_maxNoiseWakeupRange), FormatFloat(monsterAI.m_wakeUpDelayMin), FormatFloat(monsterAI.m_wakeUpDelayMax), FormatFloat(monsterAI.m_fallAsleepDistance))}");
            AppendLine(builder, 2, $"avoidLand: {FormatBool(monsterAI.m_avoidLand)}");
            return;
        }
    }

    private static void AppendLevelVisualReferenceEntry(StringBuilder builder, GameObject prefab)
    {
        LevelEffects levelEffects = prefab.GetComponentInChildren<LevelEffects>(true);
        if (levelEffects?.m_levelSetups == null || levelEffects.m_levelSetups.Count == 0)
        {
            return;
        }

        AppendListEntry(builder, 0, "prefab", prefab.name);
        AppendLine(builder, 1, "levelEffects:");
        AppendLine(builder, 2, $"component: {FormatYamlString(GetObjectPath(prefab.transform, levelEffects.transform))}");
        AppendLine(builder, 2, $"mainRenderer: {FormatYamlString(GetObjectPath(prefab.transform, levelEffects.m_mainRender != null ? levelEffects.m_mainRender.transform : null))}");
        AppendLine(builder, 2, $"baseEnableObject: {FormatYamlString(GetObjectPath(prefab.transform, levelEffects.m_baseEnableObject != null ? levelEffects.m_baseEnableObject.transform : null))}");
        AppendLine(builder, 2, "levels:");

        for (int index = 0; index < levelEffects.m_levelSetups.Count; index++)
        {
            LevelEffects.LevelSetup setup = levelEffects.m_levelSetups[index];
            if (setup == null)
            {
                continue;
            }

            List<string> values = new()
            {
                $"scale: {FormatFloat(setup.m_scale)}",
                $"hsv: {FormatInlineRawList(FormatFloat(setup.m_hue), FormatFloat(setup.m_saturation), FormatFloat(setup.m_value))}"
            };

            if (setup.m_setEmissiveColor)
            {
                values.Add($"emissive: {FormatColorTuple(setup.m_emissiveColor)}");
            }

            string enableObjectPath = GetObjectPath(prefab.transform, setup.m_enableObject != null ? setup.m_enableObject.transform : null);
            if (enableObjectPath.Length > 0)
            {
                values.Add($"enableObject: {FormatYamlString(enableObjectPath)}");
            }

            AppendLine(builder, 3, $"{index + 2}: {{ {string.Join(", ", values)} }}");
        }
    }

    private static bool HasAnyMessage(BaseAI ai)
    {
        return !string.IsNullOrWhiteSpace(ai.m_spawnMessage) ||
               !string.IsNullOrWhiteSpace(ai.m_deathMessage) ||
               !string.IsNullOrWhiteSpace(ai.m_alertedMessage);
    }

    private static void AppendAttackDamage(StringBuilder builder, int indent, ItemDrop.ItemData.SharedData shared)
    {
        HitData.DamageTypes damages = shared.m_damages;
        List<string> values = new();
        AddDamage(values, "damage", damages.m_damage);
        AddDamage(values, "blunt", damages.m_blunt);
        AddDamage(values, "slash", damages.m_slash);
        AddDamage(values, "pierce", damages.m_pierce);
        AddDamage(values, "chop", damages.m_chop);
        AddDamage(values, "pickaxe", damages.m_pickaxe);
        AddDamage(values, "fire", damages.m_fire);
        AddDamage(values, "frost", damages.m_frost);
        AddDamage(values, "lightning", damages.m_lightning);
        AddDamage(values, "poison", damages.m_poison);
        AddDamage(values, "spirit", damages.m_spirit);
        AddDamage(values, "attackForce", shared.m_attackForce);
        if (shared.m_toolTier != 0)
        {
            values.Add($"toolTier: {shared.m_toolTier.ToString(CultureInfo.InvariantCulture)}");
        }

        if (values.Count == 0)
        {
            return;
        }

        AppendLine(builder, indent, $"damage: {{ {string.Join(", ", values)} }}");
    }

    private static void AddDamage(List<string> values, string key, float value)
    {
        if (!Mathf.Approximately(value, 0f))
        {
            values.Add($"{key}: {FormatFloat(value)}");
        }
    }

    private static void AppendDamageModifiers(StringBuilder builder, HitData.DamageModifiers modifiers, int indent)
    {
        foreach ((string key, HitData.DamageModifier value) in EnumerateDamageModifiers(modifiers))
        {
            AppendLine(builder, indent, $"{key}: {value}");
        }
    }

    private static void AppendReferenceDamageModifiers(StringBuilder builder, HitData.DamageModifiers modifiers, int indent)
    {
        List<(string Key, HitData.DamageModifier Value)> values = EnumerateDamageModifiers(modifiers)
            .Where(entry => !IsReferenceDefaultDamageModifier(entry.Key, entry.Value))
            .ToList();
        if (values.Count == 0)
        {
            return;
        }

        AppendLine(builder, indent, "damageModifiers:");
        foreach ((string key, HitData.DamageModifier value) in values)
        {
            AppendLine(builder, indent + 1, $"{key}: {value}");
        }
    }

    private static bool IsReferenceDefaultDamageModifier(string key, HitData.DamageModifier value)
    {
        if (value == HitData.DamageModifier.Normal)
        {
            return true;
        }

        return (key == "chop" || key == "pickaxe") && value == HitData.DamageModifier.Ignore;
    }

    private static IEnumerable<(string Key, HitData.DamageModifier Value)> EnumerateDamageModifiers(HitData.DamageModifiers modifiers)
    {
        yield return ("blunt", modifiers.m_blunt);
        yield return ("slash", modifiers.m_slash);
        yield return ("pierce", modifiers.m_pierce);
        yield return ("chop", modifiers.m_chop);
        yield return ("pickaxe", modifiers.m_pickaxe);
        yield return ("fire", modifiers.m_fire);
        yield return ("frost", modifiers.m_frost);
        yield return ("lightning", modifiers.m_lightning);
        yield return ("poison", modifiers.m_poison);
        yield return ("spirit", modifiers.m_spirit);
    }

    private static void AppendHumanoidBlock(StringBuilder builder, GameObject prefab, int indent)
    {
        Humanoid humanoid = prefab.GetComponent<Humanoid>();
        if (humanoid == null)
        {
            return;
        }

        AppendLine(builder, indent, "humanoid:");
        AppendDefaultItems(builder, indent + 1, humanoid.m_defaultItems);
        AppendItemList(builder, indent + 1, "randomWeapon", humanoid.m_randomWeapon);
        GetRandomArmorAndHairForOutput(prefab, humanoid, out GameObject[] randomArmor, out GameObject[] randomHair);
        AppendItemList(builder, indent + 1, "randomArmor", randomArmor);
        AppendItemList(builder, indent + 1, "randomHair", randomHair);
        AppendItemList(builder, indent + 1, "randomShield", humanoid.m_randomShield);
        AppendRandomItems(builder, indent + 1, humanoid.m_randomItems);
        AppendRandomSets(builder, indent + 1, humanoid.m_randomSets);
    }

    private static void GetRandomArmorAndHairForOutput(
        GameObject creaturePrefab,
        Humanoid humanoid,
        out GameObject[] randomArmor,
        out GameObject[] randomHair)
    {
        GameObject[] sourceArmor = humanoid.m_randomArmor ?? Array.Empty<GameObject>();
        if (CreatureDomainManager.TryGetRandomHairPrefabs(creaturePrefab, out IReadOnlyList<GameObject> configuredHair))
        {
            randomArmor = sourceArmor;
            randomHair = configuredHair.Where(item => item != null).ToArray();
            return;
        }

        if (CreatureDomainManager.IsConfirmedHairOnly(sourceArmor))
        {
            randomArmor = Array.Empty<GameObject>();
            randomHair = sourceArmor;
            return;
        }

        randomArmor = sourceArmor;
        randomHair = Array.Empty<GameObject>();
    }

    private static void AppendDefaultItems(StringBuilder builder, int indent, GameObject[]? items)
    {
        List<GameObject> itemList = items?
            .Where(item => item != null)
            .GroupBy(item => item.name, StringComparer.OrdinalIgnoreCase)
            .Select(group => group.First())
            .ToList() ?? new List<GameObject>();

        if (itemList.Count == 0)
        {
            AppendLine(builder, indent, "defaultItems: []");
            return;
        }

        List<string> names = itemList
            .OrderByDescending(CreaturePrefabRegistry.IsAttackItem)
            .ThenBy(item => item.name, StringComparer.OrdinalIgnoreCase)
            .Select(item => item.name)
            .ToList();

        AppendLine(builder, indent, "defaultItems:");
        foreach (string name in names)
        {
            AppendLine(builder, indent + 1, $"- {FormatYamlString(name)}");
        }
    }

    private static void AppendItemList(StringBuilder builder, int indent, string key, GameObject[]? items)
    {
        List<string> names = items?
            .Where(item => item != null)
            .Select(item => item.name)
            .ToList() ?? new List<string>();

        if (names.Count == 0)
        {
            AppendLine(builder, indent, $"{key}: []");
            return;
        }

        AppendLine(builder, indent, $"{key}:");
        foreach (string name in names)
        {
            AppendLine(builder, indent + 1, $"- {FormatYamlString(name)}");
        }
    }

    private static void AppendRandomItems(StringBuilder builder, int indent, Humanoid.RandomItem[]? randomItems)
    {
        List<string> lines = randomItems?
            .Where(item => item?.m_prefab != null)
            .Select(item => $"{item.m_prefab.name}, {FormatFloat(item.m_chance)}")
            .ToList() ?? new List<string>();

        if (lines.Count == 0)
        {
            AppendLine(builder, indent, "randomItems: []");
            return;
        }

        AppendLine(builder, indent, "randomItems:");
        foreach (string line in lines)
        {
            AppendLine(builder, indent + 1, $"- {FormatYamlString(line)}");
        }
    }

    private static void AppendRandomSets(StringBuilder builder, int indent, Humanoid.ItemSet[]? randomSets)
    {
        List<string> lines = randomSets?
            .Where(set => set?.m_items != null)
            .Select(set => $"{set.m_name}, {string.Join(", ", set.m_items.Where(item => item != null).Select(item => item.name))}".TrimEnd(' ', ','))
            .Where(line => line.IndexOf(',') >= 0)
            .ToList() ?? new List<string>();

        if (lines.Count == 0)
        {
            AppendLine(builder, indent, "randomSets: []");
            return;
        }

        AppendLine(builder, indent, "randomSets:");
        foreach (string line in lines)
        {
            AppendLine(builder, indent + 1, $"- {FormatYamlString(line)}");
        }
    }

    private static void AppendAppearance(StringBuilder builder, GameObject prefab, int indent)
    {
        VisEquipment visEquipment = prefab.GetComponent<VisEquipment>();
        Humanoid humanoid = prefab.GetComponent<Humanoid>();
        if (visEquipment == null && humanoid == null)
        {
            return;
        }

        int modelIndex = visEquipment?.m_modelIndex ?? 0;
        Vector3 skinColor = visEquipment?.m_skinColor ?? Vector3.one;
        Vector3 hairColor = visEquipment?.m_hairColor ?? Vector3.one;
        string hair = FirstNonEmpty(humanoid?.m_hairItem, visEquipment?.m_hairItem);
        string beard = FirstNonEmpty(humanoid?.m_beardItem, visEquipment?.m_beardItem);
        bool hasHairColor = !IsWhite(hairColor);
        bool hasSkinColor = !IsWhite(skinColor);
        if (hair.Length == 0 && beard.Length == 0 && !hasHairColor && !hasSkinColor && modelIndex == 0)
        {
            return;
        }

        AppendLine(builder, indent, "appearance:");
        if (hair.Length > 0)
        {
            AppendLine(builder, indent + 1, $"hair: {FormatYamlString(hair)}");
        }

        if (beard.Length > 0)
        {
            AppendLine(builder, indent + 1, $"beard: {FormatYamlString(beard)}");
        }

        if (hasHairColor)
        {
            AppendLine(builder, indent + 1, $"hairColor: {FormatYamlString(FormatColor(hairColor))}");
        }

        if (hasSkinColor)
        {
            AppendLine(builder, indent + 1, $"skinColor: {FormatYamlString(FormatColor(skinColor))}");
        }

        if (modelIndex != 0)
        {
            AppendLine(builder, indent + 1, $"modelIndex: {modelIndex.ToString(CultureInfo.InvariantCulture)}");
        }
    }

    private static string FirstNonEmpty(string? primary, string? fallback)
    {
        return !string.IsNullOrWhiteSpace(primary)
            ? primary!
            : !string.IsNullOrWhiteSpace(fallback)
                ? fallback!
                : "";
    }

    private static List<string> GetPrimaryTextureSlots(GameObject prefab)
    {
        Renderer? renderer = FindPrimaryRenderer(prefab);
        if (renderer == null)
        {
            return new List<string>();
        }

        List<string> slots = new();
        Material[] materials = renderer.sharedMaterials;
        for (int index = 0; index < materials.Length; index++)
        {
            if (TryGetMainTexture(materials[index], out Texture texture))
            {
                slots.Add($"{renderer.name}:{index}:{texture.name}");
            }
        }

        return slots;
    }

    private static Renderer? FindPrimaryRenderer(GameObject prefab)
    {
        return prefab
            .GetComponentsInChildren<Renderer>(true)
            .Where(renderer => renderer != null && HasTextureMaterial(renderer) && !IsEffectRenderer(renderer))
            .Select(renderer => new { Renderer = renderer, Score = GetPrimaryRendererScore(prefab, renderer) })
            .Where(entry => entry.Score > int.MinValue / 2)
            .OrderByDescending(entry => entry.Score)
            .ThenBy(entry => GetTransformPath(prefab.transform, entry.Renderer.transform), StringComparer.OrdinalIgnoreCase)
            .Select(entry => entry.Renderer)
            .FirstOrDefault();
    }

    private static bool HasTextureMaterial(Renderer renderer)
    {
        return renderer.sharedMaterials.Any(material => TryGetMainTexture(material, out _));
    }

    private static bool IsEffectRenderer(Renderer renderer)
    {
        string rendererTypeName = renderer.GetType().Name;
        if (string.Equals(rendererTypeName, "ParticleSystemRenderer", StringComparison.Ordinal) ||
            string.Equals(rendererTypeName, "TrailRenderer", StringComparison.Ordinal) ||
            string.Equals(rendererTypeName, "LineRenderer", StringComparison.Ordinal))
        {
            return true;
        }

        string text = (renderer.name + "/" + GetTransformPath(null, renderer.transform)).ToLowerInvariant();
        string[] effectTokens =
        {
            "fx", "vfx", "sfx", "particle", "particles", "smoke", "mist", "splash",
            "splsh", "flies", "ooz", "wet", "water", "dust", "fire", "flame", "glow"
        };

        return effectTokens.Any(token => text.Contains(token));
    }

    private static int GetPrimaryRendererScore(GameObject prefab, Renderer renderer)
    {
        string rendererName = renderer.name ?? "";
        string path = GetTransformPath(prefab.transform, renderer.transform);
        string searchable = (rendererName + "/" + path).ToLowerInvariant();
        string prefabName = prefab.name ?? "";
        int score = 0;

        if (renderer is SkinnedMeshRenderer)
        {
            score += 100;
        }

        if (string.Equals(rendererName, prefabName, StringComparison.OrdinalIgnoreCase))
        {
            score += 120;
        }
        else if (prefabName.Length > 0 && searchable.Contains(prefabName.ToLowerInvariant()))
        {
            score += 80;
        }

        if (ContainsAny(searchable, "body", "character", "model", "mesh", "main", "root"))
        {
            score += 50;
        }

        if (ContainsAny(searchable, "lod", "ragdoll", "collider", "shadow"))
        {
            score -= 40;
        }

        return score;
    }

    private static bool ContainsAny(string value, params string[] tokens)
    {
        return tokens.Any(token => value.Contains(token));
    }

    private static string GetTransformPath(Transform? root, Transform transform)
    {
        Stack<string> parts = new();
        Transform? current = transform;
        while (current != null && current != root)
        {
            parts.Push(current.name);
            current = current.parent;
        }

        return string.Join("/", parts);
    }

    private static string GetObjectPath(Transform root, Transform? transform)
    {
        if (transform == null)
        {
            return "";
        }

        string path = GetTransformPath(root, transform);
        return string.IsNullOrWhiteSpace(path) ? "." : path;
    }

    private static bool TryGetMainTexture(Material? material, out Texture texture)
    {
        texture = null!;
        if (material == null || !material.HasProperty(MainTextureProperty))
        {
            return false;
        }

        Texture? candidate = material.GetTexture(MainTextureProperty);
        if (candidate == null)
        {
            return false;
        }

        texture = candidate;
        return true;
    }

    private static string? GetAttackAnimation(GameObject item)
    {
        ItemDrop itemDrop = item.GetComponent<ItemDrop>();
        return itemDrop?.m_itemData?.m_shared?.m_attack?.m_attackAnimation;
    }

    private static void AppendGeneratedHeader(StringBuilder builder, string artifactKind)
    {
        builder.AppendLine($"# Generated by CreatureManager ({artifactKind}).");
        if (artifactKind.IndexOf("AI", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            builder.AppendLine("# Use 'ai: prefabName' in creatures.yml to copy an existing creature prefab's AI directly.");
            builder.AppendLine("# Copy entries into ai.yml or ai_*.yml only when creating a custom reusable preset.");
            builder.AppendLine("# See ai.yml for schema notes.");
        }
        else if (artifactKind.IndexOf("attack", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            builder.AppendLine("# Copy entries into attacks.yml or attacks_*.yml before editing.");
            builder.AppendLine("# See attacks.yml for schema notes.");
        }
        else if (artifactKind.IndexOf("level visual", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            builder.AppendLine("# Lists loaded creature prefabs with LevelEffects setup data, grouped by best-effort owner.");
            builder.AppendLine("# Vanilla level 2 uses the first setup, level 3 uses the second setup, and so on.");
            builder.AppendLine("# hsv is [hue, saturation, value]. enableObject is the optional object toggled on for that level.");
        }
        else
        {
            builder.AppendLine("# Copy entries into creatures.yml or creatures_*.yml before editing.");
            builder.AppendLine(artifactKind.IndexOf("full", StringComparison.OrdinalIgnoreCase) >= 0
                ? "# Full scaffold includes humanoid loadout fields and body textures entries."
                : "# Compact reference omits humanoid loadouts and texture entries; use cm:full creature for those.");
            if (artifactKind.IndexOf("full", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                builder.AppendLine("# A randomArmor list is emitted as randomHair only when every entry is a confirmed attachable hair item.");
            }
            builder.AppendLine("# See creatures.yml for schema notes.");
            builder.AppendLine("# Configure attack prefab details in attacks.yml.");
            builder.AppendLine("# Configure reusable MonsterAI presets in ai.yml.");
            builder.AppendLine("# Drop, spawn, and detailed attack fields are intentionally not scaffolded here.");
        }

        builder.AppendLine();
    }

    private static void AppendListEntry(StringBuilder builder, int indent, string key, string value)
    {
        AppendLine(builder, indent, $"- {key}: {FormatYamlString(value)}");
    }

    private static void AppendLine(StringBuilder builder, int indent, string line)
    {
        builder.Append(' ', indent * 2);
        builder.AppendLine(line);
    }

    private static string FormatBool(bool value)
    {
        return value ? "true" : "false";
    }

    private static string FormatFloat(float value)
    {
        return value.ToString("0.###", CultureInfo.InvariantCulture);
    }

    private static string FormatTuple(params float[] values)
    {
        return string.Join(", ", values.Select(FormatFloat));
    }

    private static string FormatTuple(bool first, params float[] values)
    {
        return $"{FormatBool(first)}, {FormatTuple(values)}";
    }

    private static string FormatBossTuple(Character character)
    {
        return $"{FormatBool(character.m_boss)}, {FormatBool(character.m_dontHideBossHud)}, {FormatYamlString(character.m_bossEvent)}";
    }

    private static string FormatColor(Vector3 color)
    {
        int r = Mathf.RoundToInt(Mathf.Clamp01(color.x) * 255f);
        int g = Mathf.RoundToInt(Mathf.Clamp01(color.y) * 255f);
        int b = Mathf.RoundToInt(Mathf.Clamp01(color.z) * 255f);
        return $"#{r:X2}{g:X2}{b:X2}";
    }

    private static string FormatColorTuple(Color color)
    {
        return FormatInlineRawList(FormatFloat(color.r), FormatFloat(color.g), FormatFloat(color.b), FormatFloat(color.a));
    }

    private static bool IsWhite(Vector3 color)
    {
        return Mathf.Approximately(color.x, 1f) &&
               Mathf.Approximately(color.y, 1f) &&
               Mathf.Approximately(color.z, 1f);
    }

    private static string FormatInlineList(IEnumerable<string> values)
    {
        string[] formattedValues = values.Select(FormatYamlString).ToArray();
        return "[" + string.Join(", ", formattedValues) + "]";
    }

    private static string FormatWeightedPrefabInlineList(IEnumerable<string> prefabNames)
    {
        List<string> orderedNames = new();
        Dictionary<string, int> countsByName = new(StringComparer.Ordinal);
        foreach (string prefabName in prefabNames)
        {
            if (countsByName.TryGetValue(prefabName, out int count))
            {
                countsByName[prefabName] = count + 1;
            }
            else
            {
                orderedNames.Add(prefabName);
                countsByName[prefabName] = 1;
            }
        }

        return FormatInlineList(orderedNames.Select(prefabName =>
            countsByName[prefabName] == 1 && prefabName.IndexOf(':') < 0
                ? prefabName
                : $"{prefabName}:{countsByName[prefabName]}"));
    }

    private static string FormatInlineRawList(params string[] values)
    {
        return "[" + string.Join(", ", values) + "]";
    }

    private static string FormatYamlString(string? value)
    {
        value ??= "";
        if (value.Length == 0)
        {
            return "''";
        }

        bool requiresQuotes =
            char.IsWhiteSpace(value[0]) ||
            char.IsWhiteSpace(value[value.Length - 1]) ||
            value.IndexOfAny(new[] { ':', '#', '{', '}', '[', ']', ',', '\'', '"', '&', '*', '!', '|', '>', '%', '@', '`' }) >= 0 ||
            value[0] == '-' ||
            value[0] == '?' ||
            string.Equals(value, "null", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);

        return requiresQuotes ? $"'{value.Replace("'", "''")}'" : value;
    }
}
